version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://jx099.com:exir32ps7XATcFz8@1Panel-mysql-oh7c:3306/jx099.com
      - NEXTAUTH_SECRET=8KQzp2nx893KJFmxnv6uqwerty12378HOPxmMs4
      - NEXTAUTH_URL=http://jx099.com
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 