version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: jx099-nextjs
    container_name: jx099-nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL="mysql://root:mysql_jYAwsS@207.211.179.194/:3306/jx099?connection_limit=5&pool_timeout=2&charset=utf8mb4_unicode_ci&max_allowed_packet=16777216"
      - NEXTAUTH_SECRET=8KQzp2nx893KJFmxnv6uqwerty12378HOPxmMs4
      - NEXTAUTH_URL=https://jx099.com
      - ADMIN_SETUP_KEY=8KQzp2nx893KJFmxnv6uqwerty12378HOPxmMs4
      - NODE_ENV=production
    volumes:
      - ./index/uploads:/app/public/uploads
      - ./index/prisma:/app/prisma
      - ./ssl:/app/ssl
    networks:
      - openresty_net
    user: "1000:1000"

networks:
  openresty_net:
    external: true 